
variables:
  - template: .azure-pipelines/variables.yml

name: ${{variables.name}}-pipeline

schedules:
  - cron: "0 8 * * 5"
    displayName: Weekly run on Friday
    branches:
      include:
        - main
    always: true

stages:
  - stage: run
    displayName: Run
    jobs:
    - job: run
      displayName: Setup and Run
      pool:
        vmImage: ${{variables.vmImage}}
      steps:
      - task: Cache@2
        inputs:
          key: aws-nuke | "$(Agent.OS)" | do.sh
          path: bin
      - bash: |
          ./do.sh setup
        displayName: 'Setup'
      - bash: |
          ./do.sh info > log/aws-nuke-info.txt
        displayName: 'Info'
      - bash: |
          CURRENT_TIMESTAMP=$(./do.sh timestamp)
          echo "Timestamp: $CURRENT_TIMESTAMP"
          echo "##vso[task.setvariable variable=timestamp;]$CURRENT_TIMESTAMP"
        displayName: 'Set Timestamp'
      - task: AWSShellScript@1
        displayName: 'Run'
        inputs:
          awsCredentials: 'sje-aws-labs'
          regionName: 'eu-west-1'
          scriptType: 'inline'
          inlineScript: ./do.sh headless:${{variables.awsNukeMode}} ${{variables.awsNukeConfig}} $(timestamp)
      - publish: log
        artifact: ${{variables.name}}-${{variables.awsNukeConfig}}-$(system.JobId)-logs 
        condition: always()
      - task: S3Upload@1
        condition: always()
        inputs:
          awsCredentials: 'sje-aws-origin'
          regionName: 'eu-west-1'
          bucketName: ${{variables.logsS3Bucket}}
          sourceFolder: 'log'
          globExpressions: '**'
          targetFolder: ${{variables.name}}/${{variables.awsNukeConfig}}/$(timestamp)
          keyManagement: 'awsManaged'
