
variables:
  - template: .azure-pipelines/variables.yml

name: ${{variables.name}}-pipeline

trigger:
  - main

schedules:
  - cron: "30 8 * * 5"
    displayName: Weekly run on Friday
    branches:
      include:
        - main
    always: true

stages:
  - stage: run
    displayName: Run
    jobs:
    - job: run
      displayName: Setup and Run
      pool:
        vmImage: ${{variables.vmImage}}
      steps:
      - task: Cache@2
        inputs:
          key: "${{variables.name}}" | "$(Agent.OS)" | do.sh
          path: bin
      - bash: |
          ./do.sh setup
        displayName: 'Setup'
      - bash: |
          ./do.sh info > log/aws-nuke-info.txt
        displayName: 'Info'
      - template: .azure-pipelines/run-aws-nuke.yml
        parameters:
          name: ${{ variables.name }}
          targetServiceConnection: ${{ variables.targetServiceConnection }}
          logArchiveServiceConnection: ${{ variables.logArchiveServiceConnection }}
          awsRegion: ${{ variables.awsRegion }}
          awsNukeConfig: ${{ variables.awsConfig }}
          awsNukeMode: ${{ variables.awsNukeMode }}
          logsS3Bucket: ${{ variables.logsS3Bucket }}
