
variables:
  - template: .azure-pipelines/variables.yml

name: ${{variables.name}}-pipeline

stages:
  - stage: run
    displayName: Run
    jobs:
    - job: run
      displayName: Setup and Run
      pool:
        vmImage: ${{variables.vmImage}}
      steps:
      - task: Cache@2
        inputs:
          key: aws-nuke | "$(Agent.OS)" | do.sh
          path: bin
      - script: |
          ./do.sh setup
        displayName: 'Setup'
      - script: |
          ./do.sh info > log/aws-nuke-info.txt
        displayName: 'Info'
      - task: AWSShellScript@1
        displayName: 'Run'
        inputs:
          awsCredentials: 'sje-aws-labs'
          regionName: 'eu-west-1'
          scriptType: 'inline'
          inlineScript: ./do.sh headless:${{variables.awsNukeMode}} ${{variables.awsNukeConfig}}
      - publish: log
        artifact: ${{variables.name}}-${{variables.awsNukeConfig}}-$(system.JobId)-logs 
