
variables:
  - template: .azure-pipelines/variables.yml

name: ${{variables.name}}-pipeline

schedules:
  - cron: "0 10 * * 0"
    displayName: Weekly run on Sunday
    branches:
      include:
        - main
    always: true

stages:
  - stage: run
    displayName: Run
    jobs:
    - job: run
      displayName: Setup and Run
      pool:
        vmImage: ${{variables.vmImage}}
      steps:
      - template: .azure-pipelines/run-aws-nuke.yml
        parameters:
          name: ${{ variables.name }}
          targetServiceConnection: ${{ variables.targetServiceConnection }}
          logArchiveServiceConnection: ${{ variables.logArchiveServiceConnection }}
          awsRegion: ${{ variables.awsRegion }}
          awsNukeConfig: ${{ variables.awsNukeConfig }}
          awsNukeMode: ${{ variables.awsNukeMode }}
          logsS3Bucket: ${{ variables.logsS3Bucket }}
