variables:
  - template: .azure-pipelines/variables.yml

name: ${{variables.name}}-pipeline

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - .azure-pipelines
      - azure-pipelines.yml
      - README.md

schedules:
  - cron: "0 20 * * 0"
    displayName: Weekly run on Sunday
    branches:
      include:
        - main
    always: true

stages:
  - stage: run
    displayName: Run
    condition: eq(variables['Build.SourceBranchName'], 'main')
    jobs:
      - job: run
        displayName: Setup and Run
        steps:
          - template: .azure-pipelines/run-aws-nuke.yml
            parameters:
              name: ${{ variables.name }}
              targetServiceConnection: ${{ variables.targetServiceConnection }}
              logArchiveServiceConnection: ${{ variables.logArchiveServiceConnection }}
              awsRegion: ${{ variables.awsRegion }}
              awsNukeConfig: ${{ variables.awsNukeConfig }}
              awsNukeMode: ${{ variables.awsNukeMode }}
              logsS3Bucket: ${{ variables.logsS3Bucket }}
