---
regions:
  - global # This is for all global resource types e.g. IAM
  - eu-central-1 # Frankfurt
  - eu-west-1 # Ireland
  - eu-west-2 # London
  - us-east-1 # Default AWS region

account-blocklist:
  - 119559809358

resource-types:
  excludes:
    - IAMGroup
    - IAMGroupPolicy
    - IAMGroupPolicyAttachment
    - IAMLoginProfile
    - IAMOpenIDConnectProvider
    - IAMSAMLProvider
    - IAMUser
    - IAMUserAccessKey
    - IAMUserGroupAttachment
    - IAMUserPolicy
    - IAMUserPolicyAttachment
    - IAMUserSSHPublicKey
    - IAMVirtualMFADevice
    - EC2VPC
    - EC2Subnet
    - EC2InternetGatewayAttachment
    - EC2NetworkACL
    - EC2RouteTable
    - EC2DHCPOption
    - EC2InternetGateway

accounts:
  333594256635:
    presets:
      - "common"

presets:
  common:
    filters:
      CloudFormationStack:
        - "StackSetExecutionRoleStack"
        - property: "tag:Permanent"
          value: "True"
      IAMGroup:
        - property: "tag:Permanent"
          value: "True"
      IAMGroupPolicy:
        - property: "tag:Permanent"
          value: "True"
      IAMRole:
        - "OrganizationAccountAccessRole"
        - "AWSCloudFormationStackSetExecutionRole"
        - property: "tag:Permanent"
          value: "True"
      IAMRolePolicy:
        - property: "tag:Permanent"
          value: "True"
      IAMRolePolicyAttachment:
        - "AWSCloudFormationStackSetExecutionRole -> AdministratorAccess"
        - "OrganizationAccountAccessRole -> AdministratorAccess"
        - property: "tag:Permanent"
          value: "True"
