---
regions:
  - global # This is for all global resource types e.g. IAM

account-blocklist:
  - 119559809358 # ops

accounts:
  333594256635: # labs
    presets:
      - "common"

presets:
  common:
    filters:
      # Use name globs: Groups do not support tags
      IAMGroup:
        - type: glob
          value: "Automated*"
        - type: glob
          value: "stuartellis-ops-*"
      IAMGroupPolicyAttachment:
        - type: glob
          value: "Automated* -> *"
      # aws-nuke does not support filtering IAMPolicy by tags
      IAMPolicy:
        - property: Name
          type: glob
          value: "stuartellis-*"
      IAMRole:
        - property: Name
          type: glob
          value: "stuartellis-*"
        - property: "tag:sje:purpose"
          value: "terraform-execution"
      IAMRolePolicyAttachment:
        - type: glob
          value: "stuartellis-* -> *"      
      IAMUserAccessKey:
        - type: glob
          value: "sel -> *"
        - type: glob
          value: "sje* -> *"
      IAMUserPolicyAttachment:
        - type: glob
          value: "sel -> *"
      # aws-nuke does not support filtering IAMUser by tags
      IAMUser:
        - "sel"
        - type: glob
          value: "sje-*"
      IAMUserGroupAttachment:
        - type: glob
          value: "sje-*"
      IAMLoginProfile:
        - "sel"
      IAMVirtualMFADevice:
        - "arn:aws:iam::333594256635:mfa/sel"
