---
regions:
  - eu-west-2

account-blocklist:
  - 119559809358 # ops

resource-types:
  targets:
    - CloudFormationStack

accounts:
  333594256635: # labs
    presets:
      - "common"

presets:
  common:
    filters:
      CloudFormationStack:
        - property: "tag:sje:managed-by"
          value: "CLI"
