---
regions:
  - global # This is for all global resource types e.g. IAM
  - eu-north-1
  - eu-central-1
  - eu-south-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - us-east-1

account-blocklist:
  - 333594256635 #prod

resource-types:
  targets:
    - CloudFormationStack
    - CloudFormationStackSet
    - CloudFormationType

accounts:
  119559809358: {}
