---
regions:
  - global # This is for all global resource types e.g. IAM
  - af-south-1
  - ap-east-1
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ap-northeast-1
  - ap-northeast-2
  - ca-central-1
  - eu-north-1
  - eu-central-1
  - eu-south-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - me-south-1
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2

account-blocklist:
  - 333594256635 #prod

resource-types:
  excludes:
    - IAMGroup
    - IAMGroupPolicy
    - IAMGroupPolicyAttachment
    - IAMLoginProfile
    - IAMOpenIDConnectProvider
    - IAMSAMLProvider
    - IAMUser
    - IAMUserAccessKey
    - IAMUserGroupAttachment
    - IAMUserPolicy
    - IAMUserPolicyAttachment
    - IAMUserSSHPublicKey
    - IAMVirtualMFADevice
    - EC2VPC
    - EC2Subnet
    - EC2InternetGatewayAttachment
    - EC2NetworkACL
    - EC2RouteTable
    - EC2DHCPOption
    - EC2InternetGateway

accounts:
  119559809358:
    presets:
      - "common"

presets:
  common:
    filters:
      CloudFormationStack:
        - "StackSetExecutionRoleStack"
        - property: "tag:Permanent"
          value: "True"
      IAMGroup:
        - property: "tag:Permanent"
          value: "True"
      IAMGroupPolicy:
        - property: "tag:Permanent"
          value: "True"
      IAMRole:
        - "OrganizationAccountAccessRole"
        - "AWSCloudFormationStackSetExecutionRole"
        - property: "tag:Permanent"
          value: "True"
      IAMRolePolicy:
        - property: "tag:Permanent"
          value: "True"
      IAMRolePolicyAttachment:
        - "AWSCloudFormationStackSetExecutionRole -> AdministratorAccess"
        - "OrganizationAccountAccessRole -> AdministratorAccess"
        - property: "tag:Permanent"
          value: "True"
