parameters:
  - name: name
    type: string
  - name: targetServiceConnection
    type: string
  - name: logArchiveServiceConnection
    type: string
  - name: logsS3Bucket
    type: string
  - name: awsRegion
    type: string
  - name: awsNukeMode
    type: string
  - name: awsNukeConfig
    type: string

steps:
  - task: Cache@2
    inputs:
      key: aws-nuke | "$(Agent.OS)" | aws-nuke-version
      path: bin
  - bash: |
      ./do.sh setup
    displayName: 'Setup'
  - bash: |
      ./do.sh info > log/aws-nuke-info.txt
    displayName: 'Info'
  - bash: |
      CURRENT_TIMESTAMP=$(./do.sh timestamp)
      echo "Timestamp: $CURRENT_TIMESTAMP"
      echo "##vso[task.setvariable variable=timestamp;]$CURRENT_TIMESTAMP"
    displayName: 'Set Timestamp'
  - task: AWSShellScript@1
    displayName: 'Run'
    inputs:
      awsCredentials: ${{ parameters.targetServiceConnection }}
      regionName: ${{ parameters.awsRegion }}
      scriptType: 'inline'
      inlineScript: ./do.sh headless:${{ parameters.awsNukeMode }} ${{ parameters.awsNukeConfig }} $(timestamp)
  - bash: |
      TIMESTAMP=$(timestamp) ./do.sh summarize
    displayName: 'Generate Summaries'
  - publish: log
    artifact: ${{ parameters.name }}-${{ parameters.awsNukeConfig }}-$(system.JobId)-logs 
    condition: always()
  - task: S3Upload@1
    condition: always()
    inputs:
      awsCredentials: ${{ parameters.logArchiveServiceConnection }}
      regionName: ${{ parameters.awsRegion }}
      bucketName: ${{ parameters.logsS3Bucket }}
      sourceFolder: 'log'
      globExpressions: '**'
      targetFolder: ${{ parameters.name }}/${{ parameters.awsNukeConfig }}/$(timestamp)
